ARG LITELLM_BASE_IMAGE=docker.litellm.ai/berriai/litellm@sha256:5beb4ea641e414d2034ac4a42b72bcb3bde7d64908486bd2eba652c72cf091d9
FROM ${LITELLM_BASE_IMAGE}
RUN pip install --no-cache-dir async_generator
