ARG LITELLM_BASE_IMAGE=docker.litellm.ai/berriai/litellm:main-latest@sha256:7c311546c25e7bb6e8cafede9fcd3d0d622ac636b5c9418befaa32e85dfb0186
FROM ${LITELLM_BASE_IMAGE}
RUN pip install --no-cache-dir async_generator
