#!/usr/bin/env python3
"""Project the canonical modern MCP runtime into standalone organ packages."""

from __future__ import annotations

import argparse
from pathlib import Path

from package_targets import discover_package_targets


SHARED_ROOT = Path(__file__).resolve().parent
SERVICES_ROOT = SHARED_ROOT.parent
CANONICAL = SHARED_ROOT / "modern_runtime.py"
RUNTIME_IDENTITY = SHARED_ROOT / "runtime_identity.py"
GENERATED_HEADER = (
    "# Generated by mcp/services/_shared/build_modern_runtime_vendors.py from\n"
    "# mcp/services/_shared/modern_runtime.py. Do not edit this vendored copy.\n\n"
)
GENERATED_IDENTITY_HEADER = (
    "# Generated by mcp/services/_shared/build_modern_runtime_vendors.py from\n"
    "# mcp/services/_shared/runtime_identity.py. Do not edit this vendored copy.\n\n"
)


def rendered_source() -> str:
    return GENERATED_HEADER + CANONICAL.read_text(encoding="utf-8")


def rendered_identity_source() -> str:
    return GENERATED_IDENTITY_HEADER + RUNTIME_IDENTITY.read_text(encoding="utf-8")


def target_paths() -> list[Path]:
    return [
        target.service_root / "src" / target.package / "_modern_runtime.py"
        for target in discover_package_targets(SERVICES_ROOT)
    ]


def identity_target_paths() -> list[Path]:
    return [
        target.service_root / "src" / target.package / "_runtime_identity.py"
        for target in discover_package_targets(SERVICES_ROOT)
    ]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[Path] = []
    generated = [
        (target, rendered_source()) for target in target_paths()
    ] + [
        (target, rendered_identity_source()) for target in identity_target_paths()
    ]
    for target, expected in generated:
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current == expected:
            continue
        stale.append(target)
        if not args.check:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding="utf-8")
    if args.check and stale:
        for target in stale:
            print(
                "stale generated MCP modern runtime helper: "
                f"{target.relative_to(SERVICES_ROOT.parent.parent)}"
            )
        return 1
    if not args.check:
        print(
            "projected MCP modern runtime and identity helpers to "
            f"{len(target_paths())} packages"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
