#!/usr/bin/env python3
"""Render the shared MCP owner bundle from the runtime catalog.

The bundle is a generated systemd projection. Its membership must come from
the admitted client-read contour list; candidate and effect contours are
never startup dependencies of the read bundle.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from runtime_config import CONFIG_PATH, raw_config


REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_OUTPUT = REPO_ROOT / "systemd" / "user" / "aoa-mcp-http.service"
GENERATED_HEADER = (
    "# Generated by mcp/services/_shared/build_mcp_bundle_unit.py from "
    "runtime-config.v1.json. Do not edit the Wants set by hand."
)


def _read_unit(payload: dict, service_id: str, organ_id: str) -> str:
    services = payload.get("services")
    if not isinstance(services, list):
        raise ValueError("runtime catalog has no service projections")
    service = next(
        (
            item
            for item in services
            if isinstance(item, dict) and item.get("service_id") == service_id
        ),
        None,
    )
    if not isinstance(service, dict):
        raise ValueError(f"unknown MCP service in client-read bundle: {service_id}")
    template = service.get("read_unit_template")
    if not isinstance(template, str) or not template:
        raise ValueError(f"MCP service has no read unit template: {service_id}")
    instance = service.get("read_unit_instance")
    if not isinstance(instance, str) or not instance:
        raise ValueError(f"MCP service has no read unit instance: {service_id}")
    try:
        return template.format(
            organ=organ_id,
            instance=instance,
            service_id=service_id,
            contour="read",
        )
    except (KeyError, ValueError) as exc:
        raise ValueError(f"invalid read unit template: {service_id}") from exc


def bundle_read_units(payload: dict) -> tuple[str, ...]:
    deployment = payload.get("deployment")
    if not isinstance(deployment, dict):
        raise ValueError("runtime catalog has no deployment object")
    entries = deployment.get("client_read_contours")
    if not isinstance(entries, list) or not entries:
        raise ValueError("runtime catalog has no client-read contour entries")

    units: list[str] = []
    for entry in entries:
        if not isinstance(entry, dict):
            raise ValueError("client-read contour entry must be an object")
        service_id = entry.get("service_id")
        contour_id = entry.get("contour_id")
        organ_id = entry.get("organ_id")
        if not all(
            isinstance(value, str) and value for value in (service_id, organ_id)
        ):
            raise ValueError("client-read contour entry has incomplete identity")
        if contour_id != "read":
            raise ValueError(
                "the shared MCP bundle accepts only client-read contours: "
                f"{service_id}/{contour_id}"
            )
        unit = _read_unit(payload, service_id, organ_id)
        if unit in units:
            raise ValueError(f"duplicate shared MCP bundle unit: {unit}")
        units.append(unit)
    return tuple(units)


def render_bundle_unit(payload: dict) -> str:
    lines = [
        GENERATED_HEADER,
        "",
        "[Unit]",
        "Description=AoA MCP loopback owner bundle",
    ]
    lines.extend(f"Wants={unit}" for unit in bundle_read_units(payload))
    lines.extend(
        [
            "",
            "[Service]",
            "Type=oneshot",
            "ExecStart=/usr/bin/true",
            "RemainAfterExit=yes",
            "",
            "[Install]",
            "WantedBy=default.target",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--runtime-config", type=Path, default=CONFIG_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = render_bundle_unit(raw_config(args.runtime_config))
    if args.check:
        actual = args.output.read_text(encoding="utf-8")
        if actual != expected:
            raise SystemExit(f"generated MCP bundle is stale: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
