#!/usr/bin/env python3
"""Project the declarative MCP runtime config into standalone packages."""

from __future__ import annotations

import argparse
import pprint
from pathlib import Path

from package_targets import discover_package_targets
from runtime_config import CONFIG_PATH, load_catalog, raw_config


SHARED_ROOT = Path(__file__).resolve().parent
SERVICES_ROOT = SHARED_ROOT.parent
GENERATED_HEADER = (
    "# Generated by mcp/services/_shared/build_runtime_config_vendors.py from\n"
    "# mcp/services/_shared/runtime-config.v1.json. Do not edit this vendored copy.\n\n"
)


def _metadata(targets) -> dict[str, tuple[str, str]]:
    return {
        target.service_id: (target.package_name, target.package_version)
        for target in targets
    }


def rendered_source(service_id: str, package_name: str, package_version: str) -> str:
    payload = raw_config(CONFIG_PATH)
    service = next(
        item for item in payload["services"] if item["service_id"] == service_id
    )
    service = {
        **service,
        "package_name": package_name,
        "package_version": package_version,
    }
    generated_payload = {
        "schema_version": payload["schema_version"],
        "mcp": payload["mcp"],
        "paths": payload["paths"],
        "limits": payload["limits"],
        "service": service,
    }
    literal = pprint.pformat(generated_payload, sort_dicts=False, width=100)
    return GENERATED_HEADER + f'''"""Generated runtime identity for {service_id}."""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping


@dataclass(frozen=True)
class TransportConfig:
    transport_env_var: str
    host_env_var: str
    port_env_var: str
    default_transport: str
    default_host: str
    loopback_hosts: tuple[str, ...]
    port_min: int
    port_max: int
    protocol_version: str
    legacy_protocol_version: str
    modern_only_rejection_code: int
    streamable_http_transport: str
    streamable_http_path: str
    modern_only: bool
    sdk_distribution: str
    sdk_major: int
    sdk_requirement: str
    sdk_companion_distribution: str
    tested_sdk_lock: str
    sdk_source_revision: str


@dataclass(frozen=True)
class PathConfig:
    workspace_env_var: str
    stack_root_env_var: str
    stack_source_env_var: str
    tos_root_env_var: str
    tos_root_fallback_env_var: str
    connector_repo_bindings: Mapping[str, Mapping[str, str]]
    connector_relative_template: str
    tos_relative_to_workspace: str
    stack_runtime_relative_to_workspace: str
    stack_source_relative_to_workspace: str
    stack_logs_relative_to_runtime: str
    stack_secrets_relative_to_runtime: str
    stack_services_relative_to_runtime: str
    stack_configs_relative_to_runtime: str
    stack_deployment_manifest_relative_to_runtime: str
    stack_observation_relative_to_runtime: str
    stack_overlay_relative_to_runtime: str
    stack_registry_relative_to_workspace: str
    stack_codex_executable_relative_to_workspace_template: str
    stack_orchestration_relative_to_runtime: str
    stack_canaries_relative_to_runtime: str
    stack_effects_relative_to_runtime: str
    abyss_machine_policy_env_var: str
    abyss_machine_state_env_var: str
    abyss_machine_policy_fallback_env_var: str
    abyss_machine_state_fallback_env_var: str

    def workspace_root(self, explicit: str | Path | None = None) -> Path:
        if explicit is not None:
            return Path(explicit).expanduser().resolve()
        configured = os.environ.get(self.workspace_env_var)
        if configured:
            return Path(configured).expanduser().resolve()
        stack_root = os.environ.get(self.stack_root_env_var)
        if stack_root:
            stack_path = Path(stack_root).expanduser().resolve()
            for candidate in (stack_path, *stack_path.parents):
                if (candidate / ".aoa").is_dir():
                    return candidate
        current = Path.cwd().resolve()
        for candidate in (current, *current.parents):
            if (candidate / ".aoa").is_dir():
                return candidate
        return current

    def stack_root(self, explicit: str | Path | None = None) -> Path:
        if explicit is not None:
            return Path(explicit).expanduser().resolve()
        configured = os.environ.get(self.stack_root_env_var)
        if configured:
            return Path(configured).expanduser().resolve()
        return self.workspace_root() / self.stack_runtime_relative_to_workspace

    def stack_runtime_root(self, explicit: str | Path | None = None) -> Path:
        """Return the stack deployment root, independent of its Configs view."""
        configured = explicit
        if configured is None:
            configured = os.environ.get(self.stack_root_env_var)
        if configured:
            path = Path(configured).expanduser().resolve()
            return path.parent if path.name == "Configs" else path
        return self.workspace_root() / self.stack_runtime_relative_to_workspace

    def stack_deployment_manifest_path(self, explicit: str | Path | None = None) -> Path:
        return self.stack_runtime_root(explicit) / self.stack_deployment_manifest_relative_to_runtime

    def stack_observation_path(self, explicit: str | Path | None = None) -> Path:
        return self.stack_runtime_root(explicit) / self.stack_observation_relative_to_runtime

    def stack_overlay_path(self, explicit: str | Path | None = None) -> Path:
        return self.stack_runtime_root(explicit) / self.stack_overlay_relative_to_runtime

    def stack_secrets_root(self, explicit: str | Path | None = None) -> Path:
        return self.stack_runtime_root(explicit) / self.stack_secrets_relative_to_runtime

    def stack_configs_root(self, explicit: str | Path | None = None) -> Path:
        return self.stack_runtime_root(explicit) / self.stack_configs_relative_to_runtime

    def stack_services_root(self, explicit: str | Path | None = None) -> Path:
        return self.stack_runtime_root(explicit) / self.stack_services_relative_to_runtime

    def stack_logs_root(self, explicit: str | Path | None = None) -> Path:
        return self.stack_runtime_root(explicit) / self.stack_logs_relative_to_runtime

    def stack_registry_path(self, explicit: str | Path | None = None) -> Path:
        return self.workspace_root(explicit) / self.stack_registry_relative_to_workspace

    def stack_codex_executable(self, instance: str, explicit: str | Path | None = None) -> Path:
        relative = self.stack_codex_executable_relative_to_workspace_template.format(instance=instance)
        return self.workspace_root(explicit) / relative

    def stack_orchestration_root(self, explicit: str | Path | None = None) -> Path:
        return self.stack_runtime_root(explicit) / self.stack_orchestration_relative_to_runtime

    def stack_canaries_root(self, explicit: str | Path | None = None) -> Path:
        return self.stack_runtime_root(explicit) / self.stack_canaries_relative_to_runtime

    def stack_effects_root(self, explicit: str | Path | None = None) -> Path:
        return self.stack_runtime_root(explicit) / self.stack_effects_relative_to_runtime

    def stack_source_root(self, explicit: str | Path | None = None) -> Path:
        if explicit is not None:
            return Path(explicit).expanduser().resolve()
        configured = os.environ.get(self.stack_source_env_var) or os.environ.get(self.stack_root_env_var)
        if configured:
            return Path(configured).expanduser().resolve()
        return self.workspace_root() / self.stack_source_relative_to_workspace

    def tos_root(self, explicit: str | Path | None = None) -> Path:
        if explicit is not None:
            return Path(explicit).expanduser().resolve()
        configured = os.environ.get(self.tos_root_env_var) or os.environ.get(
            self.tos_root_fallback_env_var
        )
        if configured:
            return Path(configured).expanduser().resolve()
        return self.workspace_root() / self.tos_relative_to_workspace

    def connector_repo(self, service_id: str, explicit: str | Path | None = None) -> Path:
        try:
            binding = self.connector_repo_bindings[service_id]
            connector_id = binding["connector_id"]
            env_var = binding["env_var"]
        except (KeyError, TypeError) as exc:
            raise ValueError(
                "MCP service has no connector repository binding: {{service_id!r}}"
            ) from exc
        if explicit is not None:
            return Path(explicit).expanduser().resolve()
        configured = os.environ.get(env_var)
        if configured:
            return Path(configured).expanduser().resolve()
        relative = self.connector_relative_template.format(connector_id=connector_id)
        return (self.workspace_root() / relative).resolve()

    def abyss_machine_policy_root(self, explicit: str | Path | None = None) -> Path | None:
        if explicit is not None:
            return Path(explicit).expanduser().resolve()
        configured = os.environ.get(self.abyss_machine_policy_env_var)
        if configured:
            return Path(configured).expanduser().resolve()
        fallback = os.environ.get(self.abyss_machine_policy_fallback_env_var)
        return Path(fallback).expanduser().resolve().parent if fallback else None

    def abyss_machine_state_root(self, explicit: str | Path | None = None) -> Path | None:
        if explicit is not None:
            return Path(explicit).expanduser().resolve()
        configured = os.environ.get(self.abyss_machine_state_env_var)
        if configured:
            return Path(configured).expanduser().resolve()
        fallback = os.environ.get(self.abyss_machine_state_fallback_env_var)
        return Path(fallback).expanduser().resolve().parent if fallback else None


@dataclass(frozen=True)
class RuntimeLimits:
    status_timeout_seconds: float
    search_timeout_seconds: float
    goal_lifecycle_timeout_seconds: float
    evidence_packet_timeout_seconds: float
    usage_neighborhood_timeout_seconds: float
    route_rollup_query_timeout_seconds: float
    direct_event_rollup_query_timeout_seconds: float
    protocol_probe_server_start_timeout_seconds: float
    protocol_probe_request_timeout_seconds: float
    protocol_probe_stdio_call_timeout_seconds: float
    protocol_probe_stdio_timeout_seconds: float
    protocol_probe_connect_timeout_seconds: float
    protocol_probe_process_shutdown_timeout_seconds: float
    protocol_probe_process_kill_timeout_seconds: float


@dataclass(frozen=True)
class AuthConfig:
    token_env_var: str
    credential_name: str
    auth_scope: str
    client_id: str

    def as_kwargs(self) -> dict[str, str]:
        return {{
            "token_env_var": self.token_env_var,
            "credential_name": self.credential_name,
            "auth_scope": self.auth_scope,
            "client_id": self.client_id,
        }}


@dataclass(frozen=True)
class ContourConfig:
    contour_id: str
    port: int
    auth: AuthConfig


@dataclass(frozen=True)
class ServiceConfig:
    service_id: str
    organ_id: str
    registry_organ_id: str
    runtime_executable_mode: str
    package_name: str
    package_version: str
    module: str
    server_name_template: str
    read_unit_template: str
    read_unit_instance: str
    contours: Mapping[str, ContourConfig]
    auth_manifest_credential: str | None = None
    auth_manifest_schema: str | None = None

    def contour(self, contour_id: str) -> ContourConfig:
        try:
            return self.contours[contour_id]
        except KeyError as exc:
            raise ValueError(
                "{{self.service_id}} has no MCP contour {{contour_id!r}}; "
                "expected one of {{sorted(self.contours)}}"
            ) from exc

    def server_name(self, contour_id: str = "read", profile: str | None = None) -> str:
        self.contour(contour_id)
        return self.server_name_template.format(
            contour=contour_id.replace("_", "-"),
            profile=profile or "complete",
        )

    def read_unit_name(self, organ_id: str) -> str:
        self.contour("read")
        return self.read_unit_template.format(
            organ=organ_id,
            instance=self.read_unit_instance,
            service_id=self.service_id,
            contour="read",
        )


_RAW = {literal}
_mcp = _RAW["mcp"]
_sdk = _mcp["sdk"]
_protocol = _mcp["protocol"]
_transport = _mcp["transport"]
TRANSPORT_CONFIG = TransportConfig(
    transport_env_var=_transport["transport_env_var"],
    host_env_var=_transport["host_env_var"],
    port_env_var=_transport["port_env_var"],
    default_transport=_transport["default_transport"],
    default_host=_transport["default_host"],
    loopback_hosts=tuple(_transport["loopback_hosts"]),
    port_min=_transport["port_min"],
    port_max=_transport["port_max"],
    protocol_version=_protocol["version"],
    legacy_protocol_version=_protocol["legacy_version"],
    modern_only_rejection_code=_protocol["modern_only_rejection_code"],
    streamable_http_transport=_transport["streamable_http_transport"],
    streamable_http_path=_protocol["streamable_http_path"],
    modern_only=_protocol["modern_only"],
    sdk_distribution=_sdk["distribution"],
    sdk_major=_sdk["major"],
    sdk_requirement=_sdk["requirement"],
    sdk_companion_distribution=_sdk["companion_distribution"],
    tested_sdk_lock=_sdk["tested_lock"],
    sdk_source_revision=_sdk["source_revision"],
)
PATH_CONFIG = PathConfig(**_RAW["paths"])
RUNTIME_LIMITS = RuntimeLimits(**_RAW["limits"])
_service = _RAW["service"]
SERVICE_CONFIG = ServiceConfig(
    service_id=_service["service_id"],
    organ_id=_service["organ_id"],
    registry_organ_id=_service["registry_organ_id"],
    runtime_executable_mode=_service["runtime_executable_mode"],
    package_name=_service["package_name"],
    package_version=_service["package_version"],
    module=_service["module"],
    server_name_template=_service["server_name_template"],
    read_unit_template=_service["read_unit_template"],
    read_unit_instance=_service["read_unit_instance"],
    contours={{
        contour_id: ContourConfig(
            contour_id=contour_id,
            port=contour["port"],
            auth=AuthConfig(**contour["auth"]),
        )
        for contour_id, contour in _service["contours"].items()
    }},
    auth_manifest_credential=_service.get("auth_manifest_credential"),
    auth_manifest_schema=_service.get("auth_manifest_schema"),
)
MCP_PROTOCOL_VERSION = TRANSPORT_CONFIG.protocol_version
MCP_PROTOCOL_PATH = TRANSPORT_CONFIG.streamable_http_path
MCP_SDK_MAJOR = TRANSPORT_CONFIG.sdk_major
MCP_SDK_REQUIREMENT = TRANSPORT_CONFIG.sdk_requirement
MCP_SDK_COMPANION_DISTRIBUTION = TRANSPORT_CONFIG.sdk_companion_distribution
MCP_TESTED_SDK_LOCK = TRANSPORT_CONFIG.tested_sdk_lock
'''


def target_paths(target):
    return target.service_root / "src" / target.package / "_runtime_config.py"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    targets = discover_package_targets(SERVICES_ROOT)
    catalog = load_catalog(metadata=_metadata(targets))
    if set(catalog.services) != {target.service_id for target in targets}:
        raise SystemExit("declarative MCP config and package tree have different services")
    stale: list[Path] = []
    for target in targets:
        service = catalog.service(target.service_id)
        if service.module != target.package:
            raise SystemExit(
                f"MCP config module mismatch for {target.service_id}: "
                f"{service.module} != {target.package}"
            )
        expected = rendered_source(
            target.service_id,
            target.package_name,
            target.package_version,
        )
        destination = target_paths(target)
        current = destination.read_text(encoding="utf-8") if destination.is_file() else None
        if current == expected:
            continue
        stale.append(destination)
        if not args.check:
            destination.write_text(expected, encoding="utf-8")
    if args.check and stale:
        for destination in stale:
            print(f"stale generated MCP runtime config: {destination}")
        return 1
    if not args.check:
        print(f"projected MCP runtime config to {len(targets)} standalone packages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
