#!/usr/bin/env python3
"""Project the canonical HTTP auth helper into every standalone MCP package."""

from __future__ import annotations

import argparse
from pathlib import Path


SHARED_ROOT = Path(__file__).resolve().parent
SERVICES_ROOT = SHARED_ROOT.parent
CANONICAL = SHARED_ROOT / "http_auth.py"
TARGETS = {
    "abyss-stack-mcp": "abyss_stack_mcp",
    "abyss-machine-mcp": "abyss_machine_mcp",
    "aoa-4pda-connector-mcp": "aoa_4pda_connector_mcp",
    "aoa-decisions-mcp": "aoa_decisions_mcp",
    "aoa-discord-connector-mcp": "aoa_discord_connector_mcp",
    "aoa-evals-mcp": "aoa_evals_mcp",
    "aoa-kag-mcp": "aoa_kag_mcp",
    "aoa-memo-mcp": "aoa_memo_mcp",
    "aoa-session-memory-mcp": "aoa_session_memory_mcp",
    "aoa-stats-mcp": "aoa_stats_mcp",
    "aoa-telegram-connector-mcp": "aoa_telegram_connector_mcp",
    "tos-corpus-mcp": "tos_corpus_mcp",
}
GENERATED_HEADER = (
    "# Generated by mcp/services/_shared/build_http_auth_vendors.py from\n"
    "# mcp/services/_shared/http_auth.py. Do not edit this vendored copy.\n\n"
)


def rendered_source() -> str:
    return GENERATED_HEADER + CANONICAL.read_text(encoding="utf-8")


def target_paths() -> list[Path]:
    return [
        SERVICES_ROOT / service / "src" / package / "_http_auth.py"
        for service, package in TARGETS.items()
    ]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = rendered_source()
    stale: list[Path] = []

    for target in target_paths():
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current == expected:
            continue
        stale.append(target)
        if not args.check:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding="utf-8")

    if args.check and stale:
        for target in stale:
            print(f"stale generated MCP HTTP auth helper: {target.relative_to(SERVICES_ROOT.parent.parent)}")
        return 1
    if not args.check:
        print(f"projected MCP HTTP auth helper to {len(target_paths())} standalone packages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
