from __future__ import annotations

from collections.abc import Callable, Iterable
from pathlib import Path

TextReader = Callable[[Path], str | None]

REQUIRED_FILE_PATHS = tuple(
    Path(relative_path)
    for relative_path in (
        ".agents/AGENTS.md",
        ".agents/README.md",
        ".agents/skills/AGENTS.md",
        ".agents/spark/AGENTS.md",
        ".agents/spark/README.md",
        ".agents/spark/SWARM.md",
        ".github/GITHUB_SURFACE.md",
        "DESIGN.AGENTS.md",
        "DESIGN.md",
        "compose/AGENTS.md",
        "compose/modules/32-llamacpp-inference.yml",
        "compose/modules/43-federation-router.yml",
        "compose/modules/44-llamacpp-agent-sidecar.yml",
        "compose/modules/45-rerank-api.yml",
        "compose/modules/46-rag-api.yml",
        "compose/modules/52-tos-graph.yml",
        "compose/modules/53-babelvox-tts.yml",
        "compose/modules/README.md",
        "compose/presets/README.md",
        "compose/presets/agent-federation.txt",
        "compose/presets/agent-full.txt",
        "compose/presets/agent-observability.txt",
        "compose/presets/agent-tools.txt",
        "compose/presets/intel-federation.txt",
        "compose/presets/intel-full.txt",
        "compose/presets/intel-observability.txt",
        "compose/presets/intel-tools.txt",
        "compose/profiles/README.md",
        "compose/profiles/curation.txt",
        "compose/profiles/fallback-gateway.txt",
        "compose/profiles/federation.txt",
        "compose/profiles/intel-worker.txt",
        "compose/profiles/local-worker.txt",
        "compose/profiles/rag.txt",
        "compose/profiles/reranking.txt",
        "compose/profiles/speech-fast-experimental.txt",
        "compose/profiles/substrate.txt",
        "compose/profiles/workflows.txt",
        "compose/tuning/README.md",
        "compose/tuning/llamacpp.cpu.yml",
        "compose/tuning/llamacpp.runtime-fallback.yml",
        "compose/tuning/rag.thin-host.yml",
        "config-templates/AGENTS.md",
        "config-templates/Configs/agent-api/governed-canary-catalog.json",
        "config-templates/Configs/agent-api/governed-execution-policy.yaml",
        "config-templates/Configs/agent-api/return-policy.yaml",
        "config-templates/Configs/federation/aoa-agents.yaml",
        "config-templates/Configs/federation/aoa-evals.yaml",
        "config-templates/Configs/federation/aoa-kag.yaml",
        "config-templates/Configs/federation/aoa-memo.yaml",
        "config-templates/Configs/federation/aoa-playbooks.yaml",
        "config-templates/Configs/federation/aoa-routing.yaml",
        "config-templates/Configs/federation/tos-source.yaml",
        "config-templates/Configs/federation/upstream-compatibility-bridge.json",
        "config-templates/Configs/monitoring/alloy/config.alloy",
        "config-templates/Configs/monitoring/grafana/provisioning/datasources/loki.yml",
        "config-templates/Configs/monitoring/grafana/provisioning/datasources/00-tempo.yml",
        "config-templates/Configs/monitoring/loki/loki.yml",
        "config-templates/Configs/monitoring/prometheus.yml",
        "config-templates/Configs/monitoring/tempo/tempo.yml",
        "config-templates/Configs/rag/agentic-graph.v1.json",
        "config-templates/Configs/rag/dag-jobs.v1.json",
        "config-templates/Configs/rag/sources.json",
        "config-templates/Configs/tos-graph/README.md",
        "config-templates/Configs/tos-graph/config.yaml",
        "config-templates/Configs/tts/voices.yaml",
        "config-templates/README.md",
        "config-templates/Services/aoa-browser/Dockerfile",
        "config-templates/Services/aoa-browser/app.py",
        "config-templates/Services/babelvox-tts-api/Dockerfile",
        "config-templates/Services/babelvox-tts-api/app/main.py",
        "config-templates/Services/babelvox-tts-api/requirements.txt",
        "config-templates/Services/langchain-api/Dockerfile",
        "config-templates/Services/langchain-api/app/main.py",
        "config-templates/Services/langchain-api/requirements.txt",
        "config-templates/Services/litellm/config.yaml",
        "config-templates/Services/rag-api/Dockerfile",
        "config-templates/Services/rag-api/app/main.py",
        "config-templates/Services/rag-api/requirements.txt",
        "config-templates/Services/rerank-api/Dockerfile",
        "config-templates/Services/rerank-api/app/main.py",
        "config-templates/Services/rerank-api/requirements.txt",
        "config-templates/Services/route-api/Dockerfile",
        "config-templates/Services/route-api/app/main.py",
        "config-templates/Services/route-api/requirements.txt",
        "config-templates/Services/tos-graph/Dockerfile",
        "config-templates/Services/tos-graph/app/config.py",
        "config-templates/Services/tos-graph/app/corpus_reader.py",
        "config-templates/Services/tos-graph/app/main.py",
        "config-templates/Services/tos-graph/app/models.py",
        "config-templates/Services/tos-graph/app/neo4j_store.py",
        "config-templates/Services/tos-graph/app/philosophy_reader.py",
        "config-templates/Services/tos-graph/app/projector.py",
        "config-templates/Services/tos-graph/app/ui.py",
        "config-templates/Services/tos-graph/frontend/index.html",
        "config-templates/Services/tos-graph/frontend/package-lock.json",
        "config-templates/Services/tos-graph/frontend/package.json",
        "config-templates/Services/tos-graph/frontend/src/main.ts",
        "config-templates/Services/tos-graph/frontend/src/styles.css",
        "config-templates/Services/tos-graph/frontend/tsconfig.json",
        "config-templates/Services/tos-graph/frontend/vite.config.ts",
        "config-templates/Services/tos-graph/requirements.txt",
        "docs/AGENTS.md",
        "docs/README.md",
        "docs/RELEASING.md",
        "docs/decisions/AGENTS.md",
        "docs/decisions/TEMPLATE.md",
        "docs/governance/BRANCH_POLICY.md",
        "docs/governance/QUESTBOOK_STACK_INTEGRATION.md",
        "docs/governance/README.md",
        "docs/governance/RELEASING.md",
        "docs/install/DEPLOYMENT.md",
        "docs/install/FIRST_RUN.md",
        "docs/install/README.md",
        "docs/operations/BACKUP_RESTORE.md",
        "docs/operations/LIFECYCLE.md",
        "docs/operations/README.md",
        "docs/operations/RUNBOOK.md",
        "docs/operations/SECURITY.md",
        "docs/profiles/PRESETS.md",
        "docs/profiles/PROFILES.md",
        "docs/profiles/PROFILE_RECIPES.md",
        "docs/profiles/README.md",
        "docs/routes/AUDIT.md",
        "docs/routes/README.md",
        "docs/routes/START_HERE_ROUTE_CONTRACT.md",
        "docs/runtime/ARCHITECTURE.md",
        "docs/runtime/MECHANICS.md",
        "docs/runtime/PATHS.md",
        "docs/runtime/README.md",
        "docs/runtime/SERVICE_CATALOG.md",
        "docs/runtime/SERVICE_SELECTION.md",
        "docs/runtime/STORAGE_LAYOUT.md",
        "docs/runtime/service-selection-policy.v1.json",
        "docs/testing/AGENTS.md",
        "docs/testing/README.md",
        "docs/testing/TEST_TOPOLOGY.md",
        "docs/testing/test_inventory.json",
        "docs/validation/AGENTS.md",
        "docs/validation/COMMAND_AUTHORITY.md",
        "docs/validation/README.md",
        "docs/validation/SCRIPT_TOPOLOGY.md",
        "docs/validation/VALIDATOR_TOPOLOGY.md",
        "docs/validation/script_inventory.json",
        "docs/validation/validation_lanes.json",
        "docs/validation/validator_inventory.json",
        "env/AGENTS.md",
        "mcp/AGENTS.md",
        "mcp/README.md",
        "mcp/services/AGENTS.md",
        "mcp/services/README.md",
        "mcp/services/abyss-machine-mcp/AGENTS.md",
        "mcp/services/abyss-machine-mcp/DESIGN.md",
        "mcp/services/abyss-machine-mcp/README.md",
        "mcp/services/abyss-machine-mcp/docs/BOUNDARIES.md",
        "mcp/services/abyss-machine-mcp/docs/THREAT_MODEL.md",
        "mcp/services/abyss-machine-mcp/scripts/validate_machine_mcp.py",
        "mcp/services/abyss-machine-mcp/src/abyss_machine_mcp/core.py",
        "mcp/services/abyss-machine-mcp/src/abyss_machine_mcp/server.py",
        "mcp/services/aoa-decisions-mcp/AGENTS.md",
        "mcp/services/aoa-decisions-mcp/DESIGN.md",
        "mcp/services/aoa-decisions-mcp/README.md",
        "mcp/services/aoa-decisions-mcp/docs/BOUNDARIES.md",
        "mcp/services/aoa-decisions-mcp/docs/THREAT_MODEL.md",
        "mcp/services/aoa-decisions-mcp/scripts/validate_decisions_mcp.py",
        "mcp/services/aoa-decisions-mcp/src/aoa_decisions_mcp/core.py",
        "mcp/services/aoa-decisions-mcp/src/aoa_decisions_mcp/server.py",
        "mcp/services/aoa-evals-mcp/AGENTS.md",
        "mcp/services/aoa-evals-mcp/DESIGN.md",
        "mcp/services/aoa-evals-mcp/README.md",
        "mcp/services/aoa-evals-mcp/docs/BOUNDARIES.md",
        "mcp/services/aoa-evals-mcp/docs/THREAT_MODEL.md",
        "mcp/services/aoa-evals-mcp/scripts/validate_evals_mcp.py",
        "mcp/services/aoa-evals-mcp/src/aoa_evals_mcp/core.py",
        "mcp/services/aoa-evals-mcp/src/aoa_evals_mcp/server.py",
        "mcp/services/aoa-kag-mcp/AGENTS.md",
        "mcp/services/aoa-kag-mcp/DESIGN.md",
        "mcp/services/aoa-kag-mcp/README.md",
        "mcp/services/aoa-kag-mcp/docs/BOUNDARIES.md",
        "mcp/services/aoa-kag-mcp/docs/THREAT_MODEL.md",
        "mcp/services/aoa-kag-mcp/scripts/validate_kag_mcp.py",
        "mcp/services/aoa-kag-mcp/src/aoa_kag_mcp/core.py",
        "mcp/services/aoa-kag-mcp/src/aoa_kag_mcp/server.py",
        "mcp/services/aoa-memo-mcp/AGENTS.md",
        "mcp/services/aoa-memo-mcp/DESIGN.md",
        "mcp/services/aoa-memo-mcp/README.md",
        "mcp/services/aoa-memo-mcp/docs/BOUNDARIES.md",
        "mcp/services/aoa-memo-mcp/docs/THREAT_MODEL.md",
        "mcp/services/aoa-memo-mcp/scripts/validate_memo_mcp.py",
        "mcp/services/aoa-memo-mcp/src/aoa_memo_mcp/core.py",
        "mcp/services/aoa-memo-mcp/src/aoa_memo_mcp/server.py",
        "mcp/services/aoa-session-memory-mcp/AGENTS.md",
        "mcp/services/aoa-session-memory-mcp/DESIGN.md",
        "mcp/services/aoa-session-memory-mcp/README.md",
        "mcp/services/aoa-session-memory-mcp/docs/BOUNDARIES.md",
        "mcp/services/aoa-session-memory-mcp/docs/THREAT_MODEL.md",
        "mcp/services/aoa-session-memory-mcp/scripts/validate_session_memory_mcp.py",
        "mcp/services/aoa-session-memory-mcp/src/aoa_session_memory_mcp/core.py",
        "mcp/services/aoa-session-memory-mcp/src/aoa_session_memory_mcp/server.py",
        "mcp/services/aoa-4pda-connector-mcp/AGENTS.md",
        "mcp/services/aoa-4pda-connector-mcp/DESIGN.md",
        "mcp/services/aoa-4pda-connector-mcp/README.md",
        "mcp/services/aoa-4pda-connector-mcp/docs/BOUNDARIES.md",
        "mcp/services/aoa-4pda-connector-mcp/docs/THREAT_MODEL.md",
        "mcp/services/aoa-4pda-connector-mcp/scripts/validate_4pda_connector_mcp.py",
        "mcp/services/aoa-4pda-connector-mcp/src/aoa_4pda_connector_mcp/core.py",
        "mcp/services/aoa-4pda-connector-mcp/src/aoa_4pda_connector_mcp/server.py",
        "mcp/services/aoa-telegram-connector-mcp/AGENTS.md",
        "mcp/services/aoa-telegram-connector-mcp/DESIGN.md",
        "mcp/services/aoa-telegram-connector-mcp/README.md",
        "mcp/services/aoa-telegram-connector-mcp/docs/BOUNDARIES.md",
        "mcp/services/aoa-telegram-connector-mcp/docs/THREAT_MODEL.md",
        "mcp/services/aoa-telegram-connector-mcp/scripts/validate_telegram_connector_mcp.py",
        "mcp/services/aoa-telegram-connector-mcp/src/aoa_telegram_connector_mcp/core.py",
        "mcp/services/aoa-telegram-connector-mcp/src/aoa_telegram_connector_mcp/server.py",
        "mcp/services/aoa-discord-connector-mcp/AGENTS.md",
        "mcp/services/aoa-discord-connector-mcp/DESIGN.md",
        "mcp/services/aoa-discord-connector-mcp/README.md",
        "mcp/services/aoa-discord-connector-mcp/docs/BOUNDARIES.md",
        "mcp/services/aoa-discord-connector-mcp/docs/THREAT_MODEL.md",
        "mcp/services/aoa-discord-connector-mcp/scripts/validate_discord_connector_mcp.py",
        "mcp/services/aoa-discord-connector-mcp/src/aoa_discord_connector_mcp/core.py",
        "mcp/services/aoa-discord-connector-mcp/src/aoa_discord_connector_mcp/server.py",
        "mechanics/AGENTS.md",
        "mechanics/ARTIFACT_TOPOLOGY.md",
        "mechanics/README.md",
        "mechanics/config-projection/parts/bootstrap/docs/SECRETS_BOOTSTRAP.md",
        "mechanics/config-projection/parts/rendering/docs/RENDER_TRUTH.md",
        "mechanics/diagnostic-spine/parts/diagnose-wrapper/aoa_diagnose.py",
        "mechanics/diagnostic-spine/parts/diagnose-wrapper/tests/test_aoa_diagnose.py",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/diagnostic_surface_catalog_common.py",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/docs/DIAGNOSTIC_SPINE.md",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/examples/diagnosis_companion.min.example.json",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/examples/diagnostic_anchor_ref.min.example.json",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/examples/diagnostic_session.min.example.json",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/examples/diagnostic_target.min.example.json",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/examples/repair_handoff.min.example.json",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/examples/reviewed_diagnosis_ref.min.example.json",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/generated/diagnostic_surface_catalog.min.json",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/schemas/diagnosis_companion.schema.json",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/schemas/diagnostic_anchor_ref.schema.json",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/schemas/diagnostic_session.schema.json",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/schemas/diagnostic_target.schema.json",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/schemas/repair_handoff.schema.json",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/schemas/reviewed_diagnosis_ref.schema.json",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/tests/test_diagnostic_spine_contracts.py",
        "mechanics/diagnostic-spine/parts/diagnostic-surfaces/tests/test_diagnostic_spine_surface_validator.py",
        "mechanics/diagnostic-spine/parts/doctor-readiness/docs/DOCTOR.md",
        "mechanics/diagnostic-spine/parts/doctor-readiness/docs/LOCAL_OPS_DOCTOR_SPLIT.md",
        "mechanics/diagnostic-spine/parts/doctor-readiness/tests/test_aoa_doctor.py",
        "mechanics/diagnostic-spine/parts/truth-surfaces/docs/TRUTH_SURFACES.md",
        "mechanics/federation-seams/parts/eval-seam/docs/EVAL_RUNTIME_SEAM.md",
        "mechanics/federation-seams/parts/federation-checks/tests/test_aoa_federated_check.py",
        "mechanics/federation-seams/parts/federation-checks/tests/test_langchain_api_federated.py",
        "mechanics/federation-seams/parts/federation-checks/tests/test_route_api_closure_status.py",
        "mechanics/federation-seams/parts/kag-seam/docs/KAG_RUNTIME_SEAM.md",
        "mechanics/federation-seams/parts/memo-seam/docs/MEMO_RUNTIME_SEAM.md",
        "mechanics/federation-seams/parts/playbook-seam/docs/PLAYBOOK_RUNTIME_SEAM.md",
        "mechanics/federation-seams/parts/rpg-runtime/docs/RPG_FRONTEND_PROJECTION_SEAM.md",
        "mechanics/federation-seams/parts/rpg-runtime/docs/RPG_ROUTE_API_SEAM.md",
        "mechanics/federation-seams/parts/rpg-runtime/docs/RPG_RUNTIME_BUILDERS.md",
        "mechanics/federation-seams/parts/rpg-runtime/docs/RPG_RUNTIME_COLLECTIONS.md",
        "mechanics/federation-seams/parts/rpg-runtime/examples/agent_build_snapshot.example.json",
        "mechanics/federation-seams/parts/rpg-runtime/examples/frontend_projection_bundle.example.json",
        "mechanics/federation-seams/parts/rpg-runtime/examples/quest_run_result.example.json",
        "mechanics/federation-seams/parts/rpg-runtime/examples/reputation_ledger.example.json",
        "mechanics/federation-seams/parts/rpg-runtime/generated/agent_build_snapshots.json",
        "mechanics/federation-seams/parts/rpg-runtime/generated/frontend_projection_bundles.json",
        "mechanics/federation-seams/parts/rpg-runtime/generated/quest_run_results.json",
        "mechanics/federation-seams/parts/rpg-runtime/generated/reputation_ledgers.json",
        "mechanics/federation-seams/parts/rpg-runtime/schemas/agent_build_snapshot.schema.json",
        "mechanics/federation-seams/parts/rpg-runtime/schemas/agent_build_snapshot_collection.schema.json",
        "mechanics/federation-seams/parts/rpg-runtime/schemas/frontend_projection_bundle.schema.json",
        "mechanics/federation-seams/parts/rpg-runtime/schemas/frontend_projection_bundle_collection.schema.json",
        "mechanics/federation-seams/parts/rpg-runtime/schemas/quest_run_result.schema.json",
        "mechanics/federation-seams/parts/rpg-runtime/schemas/quest_run_result_collection.schema.json",
        "mechanics/federation-seams/parts/rpg-runtime/schemas/reputation_ledger.schema.json",
        "mechanics/federation-seams/parts/rpg-runtime/schemas/reputation_ledger_collection.schema.json",
        "mechanics/federation-seams/parts/rpg-runtime/tests/test_rpg_runtime_projection.py",
        "mechanics/federation-seams/parts/tos-graph/docs/TOS_GRAPH_CURATION.md",
        "mechanics/governed-execution/parts/autonomy-status/aoa_status_autonomy.py",
        "mechanics/governed-execution/parts/autonomy-status/tests/test_aoa_status_autonomy.py",
        "mechanics/governed-execution/parts/candidate-exports/examples/runtime_artifact_hook_candidate.self-agent-checkpoint-rollout.example.json",
        "mechanics/governed-execution/parts/candidate-exports/examples/runtime_eval_evidence_selection_candidate.workhorse-local.example.json",
        "mechanics/governed-execution/parts/candidate-exports/examples/runtime_memo_export_candidate.checkpoint_export.example.json",
        "mechanics/governed-execution/parts/candidate-exports/schemas/runtime-artifact-hook-candidate.schema.json",
        "mechanics/governed-execution/parts/candidate-exports/schemas/runtime-eval-evidence-selection-candidate.schema.json",
        "mechanics/governed-execution/parts/candidate-exports/schemas/runtime-memo-export-candidate.schema.json",
        "mechanics/governed-execution/parts/candidate-exports/tests/test_runtime_eval_evidence_export.py",
        "mechanics/governed-execution/parts/governed-runner/aoa_governed_execution.py",
        "mechanics/governed-execution/parts/governed-runner/docs/GOVERNED_EXECUTION.md",
        "mechanics/governed-execution/parts/governed-runner/tests/governed_runner_test_support.py",
        "mechanics/governed-execution/parts/governed-runner/tests/test_governed_runner_edit_specs.py",
        "mechanics/governed-execution/parts/governed-runner/tests/test_governed_runner_lifecycle.py",
        "mechanics/governed-execution/parts/governed-runner/tests/test_governed_runner_paths.py",
        "mechanics/governed-execution/parts/governed-runner/tests/test_governed_runner_policy_scope.py",
        "mechanics/governed-execution/parts/governed-runner/tests/test_governed_runner_review_packets.py",
        "mechanics/governed-execution/parts/return-policy/docs/RECURRENCE_RUNTIME_POLICY.md",
        "mechanics/governed-execution/parts/return-policy/examples/runtime_return_event.workhorse-local.example.json",
        "mechanics/governed-execution/parts/return-policy/examples/runtime_return_policy.agentic-local.example.json",
        "mechanics/governed-execution/parts/return-policy/schemas/runtime-return-event.schema.json",
        "mechanics/governed-execution/parts/return-policy/schemas/runtime-return-policy.schema.json",
        "mechanics/governed-execution/parts/runtime-contracts/schemas/runtime-governed-execution-canary-catalog.schema.json",
        "mechanics/governed-execution/parts/runtime-contracts/schemas/runtime-governed-execution-policy.schema.json",
        "mechanics/governed-execution/parts/runtime-contracts/schemas/runtime-governed-execution-request.schema.json",
        "mechanics/inference-pilots/parts/local-trials/compatibility-runners/aoa-local-ai-trials",
        "mechanics/inference-pilots/parts/quiet-bridge-commands/runners/aoa-w5-pilot",
        "mechanics/inference-pilots/parts/quiet-bridge-commands/runners/aoa-w6-pilot",
        "mechanics/inference-pilots/parts/langgraph-pilot/docs/LANGGRAPH_PILOT.md",
        "mechanics/inference-pilots/parts/langgraph-pilot/requirements.txt",
        "mechanics/inference-pilots/parts/llamacpp-pilot/docs/LLAMACPP_PILOT.md",
        "mechanics/inference-pilots/parts/llamacpp-pilot/tests/test_aoa_llamacpp_pilot.py",
        "mechanics/inference-pilots/parts/local-trials/docs/LOCAL_AI_TRIALS.md",
        "mechanics/inference-pilots/parts/local-trials/docs/RUNTIME_BENCH_POLICY.md",
        "mechanics/inference-pilots/parts/local-trials/examples/runtime_benchmark.workhorse-local.example.json",
        "mechanics/inference-pilots/parts/local-trials/schemas/runtime-benchmark.schema.json",
        "mechanics/inference-pilots/parts/local-trials/tests/test_aoa_local_ai_trials.py",
        "mechanics/inference-pilots/parts/qwen-routes/tests/test_aoa_qwen_check.py",
        "mechanics/machine-fit/parts/fit-record/README.md",
        "mechanics/machine-fit/parts/fit-record/docs/MACHINE_FIT_POLICY.md",
        "mechanics/machine-fit/parts/fit-record/examples/machine-fit.public.json.example",
        "mechanics/machine-fit/parts/fit-record/schemas/schema.v1.json",
        "mechanics/machine-fit/parts/host-facts/README.md",
        "mechanics/machine-fit/parts/host-facts/examples/reference-host.public.json",
        "mechanics/machine-fit/parts/host-facts/examples/reference-host.public.json.example",
        "mechanics/machine-fit/parts/host-facts/schemas/schema.v1.json",
        "mechanics/machine-fit/parts/inference-tuning/docs/MODEL_CARDS.md",
        "mechanics/machine-fit/parts/inference-tuning/docs/MODEL_PROFILES.md",
        "mechanics/machine-fit/parts/inference-tuning/docs/model-cards/qwen3-4b-int4-ov.md",
        "mechanics/machine-fit/parts/inference-tuning/docs/model-cards/qwen3-8b-int4-ov.md",
        "mechanics/machine-fit/parts/inference-tuning/docs/model-cards/qwen3-openvino-family.md",
        "mechanics/machine-fit/parts/inference-tuning/docs/model-cards/qwen3.5-9b-gguf-llamacpp.md",
        "mechanics/machine-fit/parts/machine-bridge/README.md",
        "mechanics/machine-fit/parts/machine-bridge/docs/MACHINE_BRIDGE.md",
        "mechanics/machine-fit/parts/machine-bridge/examples/machine-bridge.public.json.example",
        "mechanics/machine-fit/parts/machine-bridge/schemas/schema.v1.json",
        "mechanics/machine-fit/parts/machine-bridge/tests/test_machine_bridge_contracts.py",
        "mechanics/machine-fit/parts/platform-adaptations/README.md",
        "mechanics/machine-fit/parts/platform-adaptations/docs/PLATFORM_ADAPTATION_POLICY.md",
        "mechanics/machine-fit/parts/platform-adaptations/examples/platform-adaptation.public.json.example",
        "mechanics/machine-fit/parts/platform-adaptations/schemas/schema.v1.json",
        "mechanics/machine-fit/parts/reference-platform/docs/REFERENCE_PLATFORM.md",
        "mechanics/machine-fit/parts/reference-platform/docs/REFERENCE_PLATFORM_SPEC.md",
        "mechanics/machine-fit/parts/windows-bridge/README.md",
        "mechanics/machine-fit/parts/windows-bridge/docs/WINDOWS_BRIDGE.md",
        "mechanics/machine-fit/parts/windows-bridge/docs/WINDOWS_PERFORMANCE.md",
        "mechanics/machine-fit/parts/windows-bridge/docs/WINDOWS_SETUP.md",
        "mechanics/runtime-lifecycle/parts/config-sync-boundary/docs/SOURCE_RUNTIME_PARITY_PACKET.md",
        "mechanics/runtime-lifecycle/parts/start-stop/docs/LIVE_RUNTIME_CUTOVER_PACKET.md",
        "mechanics/runtime-lifecycle/parts/start-stop/tests/test_aoa_warmup.py",
        "mechanics/runtime-lifecycle/parts/status-readouts/docs/GATEWAY_CACHE_POLICY.md",
        "mechanics/runtime-lifecycle/parts/status-readouts/docs/USAGE_BUDGET_POLICY.md",
        "mechanics/runtime-lifecycle/parts/status-readouts/examples/runtime_gateway_cache_status.gateway-local.example.json",
        "mechanics/runtime-lifecycle/parts/status-readouts/examples/runtime_usage_snapshot.workhorse-local.example.json",
        "mechanics/runtime-lifecycle/parts/status-readouts/schemas/runtime-gateway-cache-status.schema.json",
        "mechanics/runtime-lifecycle/parts/status-readouts/schemas/runtime-usage-snapshot.schema.json",
        "mechanics/runtime-lifecycle/parts/status-readouts/tests/test_runtime_hygiene.py",
        "mechanics/runtime-lifecycle/parts/wait-smoke/docs/INTERNAL_PROBES.md",
        "mechanics/runtime-repair/parts/a2a-return-dry-run/docs/A2A_RETURN_DRY_RUN.md",
        "mechanics/runtime-repair/parts/a2a-return-dry-run/examples/runtime_a2a_return_closeout_dry_run.example.json",
        "mechanics/runtime-repair/parts/a2a-return-dry-run/schemas/runtime-a2a-return-closeout-dry-run.schema.json",
        "mechanics/runtime-repair/parts/a2a-return-dry-run/tests/test_a2a_return_closeout_dry_run.py",
        "mechanics/runtime-repair/parts/degradation-receipts/examples/service-degradation-receipt.example.json",
        "mechanics/runtime-repair/parts/degradation-receipts/examples/service-degradation-receipt.honest-degradation.example.json",
        "mechanics/runtime-repair/parts/degradation-receipts/examples/service-degradation-receipt.retrieval-outage-honesty.example.json",
        "mechanics/runtime-repair/parts/degradation-receipts/examples/service-degradation-receipt.timeout-chaos.example.json",
        "mechanics/runtime-repair/parts/degradation-receipts/schemas/service-degradation-receipt.schema.json",
        "mechanics/runtime-repair/parts/degradation-receipts/tests/test_degradation_receipts.py",
        "mechanics/runtime-repair/parts/memo-contradiction-sidecar/tests/test_memo_contradiction_integrity_runner.py",
        "mechanics/runtime-repair/parts/repair-safe-closeout/examples/repair-safe-closeout-receipt.example.json",
        "mechanics/runtime-repair/parts/repair-safe-closeout/examples/repair-safe-closeout-receipt.retrieval-outage-honesty.example.json",
        "mechanics/runtime-repair/parts/repair-safe-closeout/examples/repair-safe-closeout-receipt.timeout-chaos.example.json",
        "mechanics/runtime-repair/parts/repair-safe-closeout/schemas/repair-safe-closeout-receipt.schema.json",
        "mechanics/runtime-repair/parts/repair-safe-closeout/tests/test_repair_safe_closeout_receipts.py",
        "memo/AGENTS.md",
        "memo/README.md",
        "quests/AGENTS.md",
        "quests/README.md",
        "quests/examples/quest_catalog.min.example.json",
        "quests/examples/quest_dispatch.min.example.json",
        "quests/schemas/quest.schema.json",
        "quests/schemas/quest_dispatch.schema.json",
        "scripts/AGENTS.md",
        "scripts/README.md",
        "scripts/validate_decision_records.py",
        "systemd/system/AGENTS.md",
        "systemd/system/README.md",
        "systemd/system/managed-units.txt",
        "systemd/user/AGENTS.md",
        "systemd/user/managed-units.txt",
        "tests/README.md",
        "tests/test_decision_records.py",
        "tests/test_questbook_surface_contracts.py",
        "tests/test_source_topology_validator_modules.py",
    )
)


def required_files(root: Path) -> set[Path]:
    return {root / relative_path for relative_path in REQUIRED_FILE_PATHS}



def validate_required_files(
    errors: list[str],
    *,
    root: Path,
    required_files: Iterable[Path],
) -> None:
    required_file_set = set(required_files)

    for path in sorted(required_file_set):
        if not path.exists():
            errors.append(f"missing required file: {path.relative_to(root)}")

    for unit_scope in ("user", "system"):
        managed_units = root / "systemd" / unit_scope / "managed-units.txt"
        if managed_units not in required_file_set:
            continue
        if not managed_units.exists():
            continue
        for line in managed_units.read_text(encoding="utf-8").splitlines():
            unit_name = line.split("#", 1)[0].strip()
            if not unit_name:
                continue
            unit_path = root / "systemd" / unit_scope / unit_name
            if not unit_path.exists():
                errors.append(
                    f"managed {unit_scope} unit is missing source skeleton: "
                    f"systemd/{unit_scope}/{unit_name}"
                )


def validate_root_residual_topology(
    errors: list[str],
    *,
    root: Path,
    read_text_func: TextReader,
) -> None:
    forbidden_paths = {
        root / "AUDIT.md": "docs/routes/AUDIT.md",
        root / "Spark": ".agents/spark/",
        root / ".github" / "README.md": ".github/GITHUB_SURFACE.md",
        root / "docs" / "START_HERE_ROUTE_CONTRACT.md": "docs/routes/START_HERE_ROUTE_CONTRACT.md",
        root / "docs" / "AUDIT.md": "docs/routes/AUDIT.md",
        root / "docs" / "ARCHITECTURE.md": "docs/runtime/ARCHITECTURE.md",
        root / "docs" / "MECHANICS.md": "docs/runtime/MECHANICS.md",
        root / "docs" / "PATHS.md": "docs/runtime/PATHS.md",
        root / "docs" / "SERVICE_CATALOG.md": "docs/runtime/SERVICE_CATALOG.md",
        root / "docs" / "STORAGE_LAYOUT.md": "docs/runtime/STORAGE_LAYOUT.md",
        root / "docs" / "DEPLOYMENT.md": "docs/install/DEPLOYMENT.md",
        root / "docs" / "FIRST_RUN.md": "docs/install/FIRST_RUN.md",
        root / "docs" / "BACKUP_RESTORE.md": "docs/operations/BACKUP_RESTORE.md",
        root / "docs" / "LIFECYCLE.md": "docs/operations/LIFECYCLE.md",
        root / "docs" / "RUNBOOK.md": "docs/operations/RUNBOOK.md",
        root / "docs" / "SECURITY.md": "docs/operations/SECURITY.md",
        root / "docs" / "PRESETS.md": "docs/profiles/PRESETS.md",
        root / "docs" / "PROFILES.md": "docs/profiles/PROFILES.md",
        root / "docs" / "PROFILE_RECIPES.md": "docs/profiles/PROFILE_RECIPES.md",
        root / "docs" / "BRANCH_POLICY.md": "docs/governance/BRANCH_POLICY.md",
        root / "docs" / "QUESTBOOK_STACK_INTEGRATION.md": "docs/governance/QUESTBOOK_STACK_INTEGRATION.md",
    }
    for path, target in forbidden_paths.items():
        if path.exists():
            errors.append(
                f"root residual topology path {path.relative_to(root)} "
                f"must live under {target}"
            )

    agents_readme = read_text_func(root / ".agents" / "README.md") or ""
    docs_readme = read_text_func(root / "docs" / "README.md") or ""
    if ".agents/spark" not in agents_readme and "spark/README.md" not in agents_readme:
        errors.append(".agents/README.md must route the Spark fast-loop lane")
    if "routes/AUDIT.md" not in docs_readme:
        errors.append("docs/README.md must route docs/routes/AUDIT.md")
    for district in (
        "routes/",
        "runtime/",
        "install/",
        "operations/",
        "profiles/",
        "governance/",
        "validation/",
        "testing/",
        "decisions/",
    ):
        if district not in docs_readme:
            errors.append(f"docs/README.md must route docs/{district}")
